export const ICategory = [
  { label: "accomodation", name: "accommodation" },
  { label: "activity", name: "activity" },
  { label: "administrative", name: "administrative" },
  { label: "amenity", name: "amenity" },
  { label: "beach", name: "beach" },
  { label: "camping", name: "camping" },
  { label: "catering", name: "catering" },
  { label: "childcare", name: "childcare" },
  { label: "education", name: "education" },
  { label: "entertainment", name: "entertainment" },
  { label: "healthcare", name: "healthcare" },
  { label: "leisure", name: "leisure" },
  { label: "low_emission_zone", name: "low_emission_zone" },
  { label: "man_made", name: "man_made" },
  { label: "natural", name: "natural" },
  { label: "national_park", name: "national_park" },
  { label: "office", name: "office" },
  { label: "parking", name: "parking" },
  { label: "pet", name: "pet" },
  { label: "political", name: "political" },
  { label: "populated_place", name: "populated_placeatural" },
  { label: "postal_code", name: "postal_code" },
  { label: "production", name: "production" },
  { label: "public_transport", name: "public_transport" },
  { label: "rental", name: "rental" },
  { label: "populated_place", name: "npopulated_placeatural" },
  { label: "service", name: "service" },
  { label: "ski", name: "ski" },
  { label: "sport", name: "sport" },
];
export const ICondition = [
  { label: "access", name: "access" },
  { label: "access_limited", name: "access_limited" },
  { label: "dogs", name: "dogs" },
  { label: "fee", name: "fee" },
  { label: "halal", name: "halal" },
  { label: "internet_access", name: "internet_access" },
  { label: "named", name: "named" },
  { label: "no_fee", name: "no_fee" },
  { label: "organic", name: "organic" },
  { label: "vegan", name: "vegan" },
  { label: "vegetarian", name: "vegetarian" },
  { label: "wheelchair", name: "wheelchair" },
];

export const IFilter = [
  { label: "Abeokuta", name: "7.145244, 3.327695" },
  { label: "Port Hacourt", name: "4.824167, 7.033611" },
  { label: "Kano", name: "12.000000, 8.526667" },
  { label: "Katsina", name: "12.985531, 7.617144" },
  { label: "Ikeja", name: "6.605874, 3.349149" },
  { label: "Ughelli", name: "5.500187, 5.5993834" },
  { label: "Akure", name: "7.250771, 5.210266" },
  { label: "Calabar", name: "4.982873, 8.334503" },
  { label: "Jos", name: "9.896527, 8.858331" },
];
